name: build_html
description: Construct HTML documents in Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.3

# Add regular dependencies here.
# dependencies:
#   web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
