name: build_html
description: Construct HTML documents in Dart.
version: 0.1.0
repository: https://github.com/thumbert/build_html

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
# dependencies:
#   web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
